### ISSUE TITLE
in resize: Expected "height" to have value >= 0.01

### ISSUE THREAD

**Issue by Kastalco520** [EightShapes/specs-plugin#101]
in resize: Expected "height" to have value >= 0.01
![image](https://github.com/EightShapes/specs-plugin/assets/64228931/dee0acbf-a96f-40ef-93a9-9f4801144535)

**Comment by nathanacurtis** [comment]
@Kastalco520  Thanks for your interest in the plugin. I recently implemented a fix to prevent failures when resizing where resizing is performed, such that this error shouldn't be occurring anymore. Could you provide more details on your component? For example...

- Do you have layers with 0 width or height?
- What kinds of node is it: FRAME, TEXT, POLYGON, etc?
- Might you be able to share a view-only access of an example for me to inspect? If you'd like it to be confidential, you could join the plugin's Slack via the link in the community page and DM me there.

Same defect as #93  and #97

**Comment by nathanacurtis** [comment]
Released version 25 that includes additional defensive measures against defects for zero height and/or zero width. Please restart Figma and retest to confirm if this defect persists or not. Otherwise, I'll close this issue in seven days if I don't hear back from you. Thanks again for your interest! :)
