### ISSUE TITLE
Plugin displays error when underlying page unloads 

### ISSUE THREAD

**Issue by amills80** [EightShapes/specs-plugin#116]
### Description

Plugin is crashing Figma tab (see screenshot). Would love to help troubleshoot. 

### Steps to reproduce

Trying to export specs for a component instance. 

### Screenshot

![image](https://github.com/EightShapes/specs-plugin/assets/8049836/6d962e46-df38-415c-ae4e-1e2579e307c5)

### Additional context

Component has many variants. Not sure what's possibly causing the issue. 

### Defect log
in setPluginData: The node (instance sublayer or table cell) with id "I2861:391780;2108:74151" does not exist

Figma ran into a problem
Our team is looking into it now. If refreshing the page doesn't work, check our [status page](https://status.figma.com/) for updates.
Error ID: 77b1d8d11c554622bb69a71b579d1004

**Comment by nathanacurtis** [comment]
Thanks for submitting this issue, and the screenshot is very helpful. The base page ("Figma ran into a problem") looks like it's a browser - Figma issue. To say it's variant quantity is only speculation on my end. To troubleshoot _that_ potential issue, you could duplicate the file, remove many variants, and continue trying to run the plugin.

I would speculate that – once the page's content flaked out – the script in the plugin kept running, reached for the next node to inspect, and there's no nodes to inspect anymore.

If you like, I'd be happy to troubleshoot in your file, or a duplicate file. If sharing access is confidential such that sharing it on this Issue is a problem, you can directly message me on the Slack linked to on the plugin's community page.

**Comment by amills80** [comment]
Hey, Nathan - just getting around to this. 
By "remove many variants", what are you suggesting? 
Detach instances from their components? 
Remove button components with hover & tap variants built in? 
I'll unearth my Slack acct in a few.

**Comment by nathanacurtis** [comment]
By "remove variants", other plugin users will carve away everything but the item they used that produced the error, particularly when concerned about confidentiality. You can share everything you feel comfortable with in a view-only file you provide access to, and I'll work from there.

**Comment by nathanacurtis** [comment]
Customer had an SVG with deep and broad layers being compared across variants, resulting in the plugin's comparison engine choking and Figma hanging. #wontfix
