### ISSUE TITLE
Error: Node does not exist

### ISSUE THREAD

**Issue by dc-international** [EightShapes/specs-plugin#120]
The plugin doesn't work when I try to create specs for a frame containing multiple nested components.

<img width="317" alt="image" src="https://github.com/EightShapes/specs-plugin/assets/115611689/d486e4e3-20f6-4ca5-84a1-239c4555ca70">

Issue text:
in remove: The node with id "1:445" does not exist

Please help. It's a blocker in my workflow now.

**Comment by nathanacurtis** [comment]
Thanks for your interest, @dc-international, and sorry you are experiencing this error.

Based on the vague error `The node with id xx.xx does not exist`, I cannot troubleshoot. I'd be happy to help, however, if you'd be able to provide a view-only Figma link to just the frame in question (often, plugin users will copy what's producing the error to a blank file so as to preserve confidentiality otherwise). If you'd like to provide that link privately, you can join the plugin's 
 [Slack community](https://join.slack.com/t/eightshapes-specs/shared_invite/zt-1w4k19pj7-viPHKW8045zak64u~lH4yA) and directly message me there.

**Comment by nathanacurtis** [comment]
This may end up being the same error as will be fixed with #121 . Haven't heard back otherwise from the submitter.
