### ISSUE TITLE
cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by papirfecnike** [EightShapes/specs-plugin#160]
After I purchased the extended version of the plugin, it stopped working, mentioning the above error message. I do everything the same as prior to purchase. Plot twist: there is no "value" property in the component, perhaps the plugin takes it as default...?

**Comment by nathanacurtis** [comment]
@papirfecnike I'm sorry to hear you've uncovered a defect. Occasionally, new subscribers run into a issue when Figma's payment platform passes control back to the plugin. So your first attempt at resolving the issue should be to restart Figma and/or your browser: Quit, restart, reload Figma file, reload plugin.

If the issue persists, in order for me to troubleshoot, I'd need access to a view-only Figma file with the offending frame, instance or component you've selected that's producing the error when you run the plugin. Otherwise, that error message is too generic for me to correct the issue.

If you'd like to share the file privately, the [Slack](https://join.slack.com/t/eightshapes-specs/shared_invite/zt-1w4k19pj7-viPHKW8045zak64u~lH4yA) for the plugin would work.

**Comment by papirfecnike** [comment]
Wow, I didn't expect such quick answer, thanks. The simple restart solved it so far. Thanks for this plugin though, it is amazing. It solves many problems for me!
    On Monday, May 20, 2024 at 12:53:37 PM GMT+2, Nathan Curtis ***@***.***> wrote:  
 
 


@papirfecnike I'm sorry to hear you've uncovered a defect. Occasionally, new subscribers run into a issue when Figma's payment platform passes control back to the plugin. So your first attempt at resolving the issue should be to restart Figma and/or your browser: Quit, restart, reload Figma file, reload plugin.

If the issue persists, in order for me to troubleshoot, I'd need access to a view-only Figma file with the offending frame, instance or component you've selected that's producing the error when you run the plugin. Otherwise, that error message is too generic for me to correct the issue.

If you'd like to share the file privately, the Slack for the plugin would work.

**Comment by nathanacurtis** [comment]
Glad it's resolved :)
