### ISSUE TITLE
The plugin encountered an error

### ISSUE THREAD

**Issue by bbontempo** [EightShapes/specs-plugin#163]
### Description

Displayed message: "The plugin encountered an error
To report this defect to the plugin author, submit an issue with this message and – if you are willing – include a link to a view-only file with the item(s) you selected so the author can reproduce the error.

cannot read property 'value' of undefined"

### Steps to reproduce

Select a component and run the plugin

### Screenshot

<img width="319" alt="Screenshot 2024-06-04 at 10 26 29" src="https://github.com/EightShapes/specs-plugin/assets/110467720/73925e1f-7a09-463c-bf24-503070c1f5b6">

### Additional context

{Add any other context about the problem here}

### Defect log

"The plugin encountered an error
To report this defect to the plugin author, submit an issue with this message and – if you are willing – include a link to a view-only file with the item(s) you selected so the author can reproduce the error.

cannot read property 'value' of undefined"

**Comment by nathanacurtis** [comment]
@bbontempo Thank you for reporting a defect. Unfortunately, the error message you shared is very common and can apply to many scenarios throughout the plugin. In order to properly troubleshoot this error, would it be possible for you to provide access only to the triggering frame or instance? I would then be able to run the plugin locally and evaluate the nature of the error. 

Plugin subscribers often provide access to a view only file or a downloadable `.fig` file that contains just that object. To share this privately, you could message me directly on the plugin's [Slack community](https://join.slack.com/t/eightshapes-specs/shared_invite/zt-1w4k19pj7-viPHKW8045zak64u~lH4yA) as well.

**Comment by bbontempo** [comment]
Hi Nathan,

There we go https://www.figma.com/design/9o1gqHSCNZknBPiK259bFe/ONGOING-variables-TEST?m=dev&node-id=789-23421&t=logqVwMiGjDKSJON-1

**Comment by nathanacurtis** [comment]
@bbontempo Thanks for sharing. There's a defect occurring when initiating the "Two way" props feature on the Icon subcomponent. I am unable to resolve this defect today, but the plugin runs successfully if you deactivate that feature. To confirm: are you a paid subscriber and were you using "Two way"?

**Comment by nathanacurtis** [comment]
@bbontempo I've issued a fix that seems to work on your use case. To confirm, restart Figma, restart the plugin, and try again.

**Comment by bbontempo** [comment]
Thanks a lot, It's working now. I'm subscribed.
