### ISSUE TITLE
Can the layouts within the specs be turned into screenshot to improve performance?

### ISSUE THREAD

**Issue by azimlich** [EightShapes/specs-plugin#172]
**Is your feature request related to a problem? Please describe.**
When a Figma file has a great deal of items, then the performance of the file goes way down as memory gets eaten up.

**Describe the solution you'd like**
If they layouts that are being speced were converted to screenshots within the specs, then the memory usage would be lower.

**Describe alternatives you've considered**
I usually have to work around this issue by copying the layouts to a new file and then running the plugin.

**Comment by nathanacurtis** [comment]
That's an interesting idea. Interestingly, a significant portion of my recent development has been to update plugin code because Figma changed how _it_ worked to improve file performance, which reduced the performance of the plugin.

Regardless, you are the first person to ask for this feature, it'd take significant development effort to make and maintain, and the feature of "Copy as PNG" already exists in Figma to do this action yourself. Therefore, unfortunately, relative to the many other priorities I have for the plugin, I cannot see me investing time to implement this feature.

I do appreciate you sharing the idea, and if other ideas occur to you please let me know.
