### ISSUE TITLE
(No defect description provided yet)

### ISSUE THREAD

**Issue by miridih-pd001** [EightShapes/specs-plugin#78]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@miridih-pd001 

Would you be able to provide more details about "not works?" For example, would you be able to provide access to a view-only version of your component so that I can inspect and reproduce the error? If you'd like to keep it confidential, you could DM me on the Slack community group linked from the plugin page.

**Comment by nathanacurtis** [comment]
Closing pending any further details provided by the issue creator.
