### ISSUE TITLE
in resize: Expected "width" to have value >= 0.01

### ISSUE THREAD

**Issue by butlerhouse** [EightShapes/specs-plugin#97]
### Description

{Describe the bug in a sentence}

### Steps to reproduce

{Add steps to reproduce the error}

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment]
@butlerhouse 
Thanks for your interest in the plugin. I recently implemented a fix to prevent failures when resizing where resizing is performed, such that this error shouldn't be occurring anymore. Could you provide more details on your component? For example...

- Do you have layers with 0 width or height?
- What kinds of node is it: FRAME, TEXT, POLYGON, etc?
- Might you be able to share a view-only access of an example for me to inspect?

**Comment by nathanacurtis** [comment]
Similar to #93

**Comment by nathanacurtis** [comment]
Released version 25 that includes additional defensive measures against defects for zero height and/or zero width. Please restart Figma and retest to confirm if this defect persists or not. Otherwise, I'll close this issue in seven days if I don't hear back from you. Thanks again for your interest! :)
