### ISSUE TITLE
Cannot read getLocalVariableCollections

### ISSUE THREAD

**Issue by michalporada** [EightShapes/specs-plugin#98]
<img width="314" alt="Screenshot 2023-06-22 at 11 02 47" src="https://github.com/EightShapes/specs-plugin/assets/25610677/3eae9266-e8f7-4633-83f0-531002803d7e">

**Comment by nathanacurtis** [comment]
@michalporada A plugin release early yesterday included a defect producing this error, and a fix was released later that day. 

* Can you close and reopen the plugin, and even Figma, to validate that the issue persists? 
* If it does, would it be possible to provide a view-only link to a file with (only) the offending item so that I can inspect it?
* Also, what Figma plan (Enterprise, Organization, Pro or Starter) do you have, and was your file placed in Drafts?

Thanks!

**Comment by nathanacurtis** [comment]
I've published a version 22 fix that "Checks for `figma.variables` when creating local variable collection".

Pro plugin features for custom spec styling and dark mode will be impaired until (presumably, upon restart) you have access to Figma's variables features.

**Comment by nathanacurtis** [comment]
Based on feedback from numerous other users that restarting Figma resolves this issue, I'm closing the issue for now. If you continue to experience the issue, feel free to reopen the issue with more details. Cheers :)
